### ISSUE TITLE
Task: Create dataframe of species locations in Arabian Sea and/or Bay of Bengal

### ISSUE THREAD

**Issue by eeholmes** [oceanhackweek/ohw23_proj_marinesdms#1]
https://seamap.env.duke.edu/

Here are some sea turtle species data available:
<img width="1105" alt="image" src="https://github.com/oceanhackweek/ohw23_proj_marinesdms/assets/2545978/f628ba71-8ea9-4174-bb0b-37a626ac0628">

Looks like more data is available on the east coast of Africa.

**Comment by 7yl4r** [comment]
The example data in `/data/raw_bio` should be fairly easy to load in. This format is similar to a Darwin Core `occurrences.csv` file.

```
"oid","longitude","latitude","providers","species","datasets","date_min","date_max","num_records","num_animals","num_species","y1_value","y2_value","y3_value","csquare","geom_wkt"
49450059,-179.5,-16.7,"The State of the World's Sea Turtles Team","Chelonia mydas","545","2006-01-01","2006-01-01",1,,1,,,,"5117:469:374","POLYGON((-179.4 -16.7,-179.4 -16.8,-179.5 -16.8,-179.5 -16.7,-179.4 -16.7))"
49450058,-179.3,-16.3,"The State of the World's Sea Turtles Team","Chelonia mydas","545","2006-01-01","2006-01-01",1,55,1,,,,"5117:469:132","POLYGON((-179.2 -16.3,-179.2 -16.4,-179.3 -16.4,-179.3 -16.3,-179.2 -16.3))"
40059319,-178.4,-30.2,"Graham Edgar, Institute for Marine and Antarctic Studies (IMAS), University of Tasmania (UTAS)","Chelonia mydas","103152531","2012-12-30","2012-12-30",1,1,1,,,,"5317:208:124","POLYGON((-178.4 -30.2,-178.4 -30.3,-178.5 -30.3,-178.5 -30.2,-178.4 -30.2))"
40060818,-178.0,-29.3,"Kevin Mackay, NIWA","Chelonia mydas","103152536","1905-05-23","1992-05-01",2,,1,,,,"5217:497:229","POLYGON((-177.9 -29.2,-177.9 -29.3,-178 -29.3,-178 -29.2,-177.9 -29.2))"
```

**Comment by marysolokas** [comment]
I created a file that gets the lat/long of the green turtles in the Arabian Sea and Bay of Bengal from the green_turtles.csv file, and I think it is in the right format to use with dismo. I'm not sure yet how to make distinction of if the turtle was on sea vs land, and currently looking for more datasets to add.

**Comment by 7yl4r** [comment]
I initiated an export from OBIS for the following query:

![image](https://github.com/oceanhackweek/ohw23_proj_marinesdms/assets/1051390/a5bd0352-addf-4834-a135-a1ef07895acf)

I should be able to upload the 8554-line .csv shortly.

**Comment by sjhong0117** [comment]
> I initiated an export from OBIS for [this query](https://mapper.obis.org/?taxonid=137206&geometry=POLYGON%20((41.1328%208.5810,%2053.2617%2028.6135,%2077.5195%2026.2737,%2091.0547%20-11.5231,%2036.3867%20-6.3153,%2041.1328%208.5810))#):
> 
> ![image](https://user-images.githubusercontent.com/1051390/259272624-a5bd0352-addf-4834-a135-a1ef07895acf.png)
> 
> I should be able to upload the 8554-line .csv shortly.

How did you do this? (I did download from the link you posted, But I really want to know how you did this. I'm just so new to using OBIS...)
