### ISSUE TITLE
Adjusted get_seaturtle_data.Rmd

### ISSUE THREAD

**Issue by caitobrien** [oceanhackweek/ohw23_proj_marinesdms#14]
@Lidefi87 Just a heads up I adjusted a few lines on the intro/end of your get_seaturtles_data.RMD to match better into the quarto.yml flow. Feel free to let me know if you have any questions.

**Comment by lidefi87** [comment]
No worries. I just added how to save a couple of files so we do not have to repeat steps in other notebooks.
