### ISSUE TITLE
Day 2: Learn about SDMs

### ISSUE THREAD

**Issue by eeholmes** [oceanhackweek/ohw23_proj_marinesdms#5]
dismo package
`library(dismo)`

**Comment by 7yl4r** [comment]
I have done it personally, but I have heard discussion of [wallace](https://wallaceecomod.github.io/wallace/index.html) as the go-to R package for SDMing.

There is a short mention of the dismo package on the wallace homepage relating to how wallace removes dismo's dependence on java so we know the wallace authors are aware of dismo and might be improving upon it.
