### ISSUE TITLE
Getting data from a zarr into R

### ISSUE THREAD

**Issue by eeholmes** [oceanhackweek/ohw23_proj_marinesdms#7]

**Comment by mackenziefiss** [comment]
my adaptation on the code from the [reading zarr into R tutorial](https://www.r-bloggers.com/2022/09/reading-zarr-files-with-r-package-stars/):

path <- 'ZARR:"/home/jovyan/shared/marine-SDMs/INDIAN_OCEAN_025GRID_DAILY.zarr"'
bounds <- c(longitude = "lon_bounds", latitude = "lat_bounds")
env.dat <- read_stars(path, bounds = bounds)

gave the error: 
Warning: Cannot find any of Zarr metadata files in '/home/jovyan/shared/marine-SDMs/INDIAN_OCEAN_025GRID_DAILY.zarr'. (GDAL error 1)trying to read file: ZARR:"/home/jovyan/shared/marine-SDMs/INDIAN_OCEAN_025GRID_DAILY.zarr"
Error in CPL_read_gdal(as.character(x), as.character(options), as.character(driver),  : 
  file not found

**Comment by mackenziefiss** [comment]
`stars` documentation: https://cran.r-project.org/web/packages/stars/stars.pdf

**Comment by eeholmes** [comment]
install Rarr remotes::install_github("grimbough/Rarr")

**Comment by eeholmes** [comment]
Giving up. Subsetting Zarr and saving as netCDF

https://pjbartlein.github.io/REarthSysSci/raster_intro.html

**Comment by 7yl4r** [comment]
FNF error seems like a file path or permissions error. I am curious what you get when trying to stat the file using `ls` and jupyterHub's bash functionality:

```
!ls -lah /home/jovyan/shared/marine-SDMs/INDIAN_OCEAN_025GRID_DAILY.zarr
```

**Comment by caitobrien** [comment]
https://github.com/oceanhackweek/ohw23_proj_marinesdms/issues/7#issuecomment-1670455960
per Valentina's (mentor) suggestion on[ slack](https://oceanhackweek.slack.com/archives/C05LQQ8HMEW/p1691539499132519) this worked for me to import the zarr file using R studio 


Instructions how to use reticulate on the hub:
1. First set up a conda environment from the jupyter lab terminal with the needed Python packages
`conda create -n xarray xarray netcdf4 zarr`
2. Go to RStudio and set up reticulate
```
install.packages("reticulate")
library(reticulate)
use_condaenv("xarray")
```
3. Now you can read the zarr file
```
xr = import("xarray")
xr$open_dataset("/home/shared/marine-SDMs/INDIAN_OCEAN_025GRID_DAILY.zarr")
```

Thoughts on sticking with this option or the netcdf route for the tutorial?

**Comment by caitobrien** [comment]
Just say no to ZARR

**Comment by lidefi87** [comment]
This [notebook](https://github.com/oceanhackweek/ohw23_proj_marinesdms/blob/main/tutorial/**_Extracting_environmental_data.ipynb)  shows how to load `zarr` files and extract data using the locations of sea turtles. Currently, it is sitting as a Jupyter notebook, but I can create a function in `Python` that we could call in `R` directly. I am thinking the function will return a data frame with the environmental variable of interest, time, and coordinates.
